Admiral-Fish/PokeFinder

Objects/LCRNG.cpp
Objects/LCRNG.hpp
Objects/NatureLock.cpp

Magic numbers and string literals are the bane of my existence. I made them go away.

I've made things a bit more readable. 

---

appveyor.yml

Better packaging

---

Core/Gen3/FrameGen3.cpp
Core/Gen3/FrameGen3.hpp
Forms/mainwindow.cpp
Forms/mainwindow.h
Forms/mainwindow.ui

Reworked how data was filled into the table to be more organized based on where the data was coming from and how it was handled.

Redone table filling

---

appveyor.yml

This pull request updates Appveyor's docker usage to use Qt 5.11.

Qt 5.11 docker

---

Core/Resources/Text/it/characteristic_it.txt
Core/Resources/Text/it/dppt_it.txt
Core/Resources/Text/it/frlg_it.txt
Core/Resources/Text/it/hgss_it.txt
Core/Resources/Text/it/rse_it.txt
i18n/PokeFinder_it.ts

Translation of the entire program

Completed Italian Translation

---

Forms/Util/Researcher.cpp

* Inserted starting seed will be the first seed in Researcher output

Make inserted starting seed the first seed in Researcher output (#123)

---

Source/Core/Gen5/Generators/DreamRadarGenerator.cpp
Source/Core/Gen5/Generators/DreamRadarGenerator.hpp
Source/Core/Gen5/Searchers/DreamRadarSearcher.cpp
Source/Core/Gen5/Searchers/DreamRadarSearcher.hpp
Source/Core/Gen5/States/DreamRadarState.hpp
Source/Forms/Models/Gen5/DreamRadarModel.cpp
Source/Forms/Models/Gen5/DreamRadarModel.hpp
Source/Forms/i18n/PokeFinder_de.ts
Source/Forms/i18n/PokeFinder_es.ts
Source/Forms/i18n/PokeFinder_fr.ts
Source/Forms/i18n/PokeFinder_it.ts
Source/Forms/i18n/PokeFinder_ja.ts
Source/Forms/i18n/PokeFinder_ko.ts
Source/Forms/i18n/PokeFinder_zh.ts

Advances in DreamRadar rng now matches perfectly in game advances. Tested many times and now perfectly working, also the researcher.

Added Key Advances column Gen5 DreamRadar

---

Source/Forms/Gen5/DreamRadar.cpp

Fix genderless in Dream Radar searcher
Added beldum

Fix genderless slots in Dream Radar Searcher and add Beldum

---

Source/Core/Gen4/Generators/WildGenerator4.cpp

[Gen4] Fix initial advances not accounted in occidentary calculation (#181)

---

Source/Core/Util/IVChecker.hpp

Adds array to compile on Linux for latest commit

Fix Linux compiling

---

Source/Core/Gen4/Generators/WildGenerator4.cpp
Source/Core/Gen4/Generators/WildGenerator4.hpp
Source/Forms/Gen4/Wild4.cpp

[Gen4] Fix gen4 occidentary wrong values (#165)

---

Source/Core/Gen5/Generators/HiddenGrottoGenerator.cpp

[Gen5] Fix hidden grotto generator/searcher advances -1 offset (#186)

---

Source/Core/Gen4/Generators/WildGenerator4.cpp
Source/Core/Gen4/Searchers/WildSearcher4.cpp
Source/Core/Gen4/States/WildState4.hpp
Source/Core/Parents/States/WildState.hpp
Source/Forms/Models/Gen4/WildModel4.cpp
Source/Forms/Models/Gen4/WildModel4.hpp

Add what requested in #183 (gen4 only).
Thanks to @ShinySylveon04 for testing it!

[Gen4] Added held item in wild generator/searcher

---

Source/Core/Enum/Method.hpp
Source/Core/Gen3/Generators/EggGenerator3.cpp
Source/Forms/Gen3/Eggs3.cpp
Source/Forms/Gen3/Eggs3.ui

Code taken from [here](https://github.com/Lincoln-LM/Finder-ToolBox/commit/bf75fd531369af8a8bacaaebfc0a2d8fcde4d7eb) and [here](https://github.com/Lincoln-LM/Finder-ToolBox/commit/c129e822dde485d389db5a2cf6b1d1bf60cce6c2).
Thanks to [Lincoln-LM](https://github.com/Lincoln-LM/)!

Added missing FRLG breeding rng method

---

Source/Forms/Models/Gen3/EggModel3.cpp

[Gen 3] Fix Emerald egg generator displaying 0 advances

---

Source/Core/Resources/i18n/zh/bdsp_zh.txt
Source/Forms/i18n/PokeFinder_zh.ts

unlock some "unfinished" but translated fields

Add Chinese translations

---

Source/Core/Gen3/EncounterArea3.cpp
Source/Core/Gen3/EncounterArea3.hpp
Source/Core/Gen3/Generators/WildGenerator3.cpp
Source/Core/Gen3/Generators/WildGenerator3.hpp
Source/Core/Gen3/Searchers/WildSearcher3.cpp
Source/Core/Gen3/Searchers/WildSearcher3.hpp
Source/Forms/Gen3/Wild3.cpp

Fix for Rock Smash generation inside Safari Zone for RSE (partial #65)

[Gen3] Fix Rock Smash in Safari Zone for RSE (partial #65)

---

Source/Core/Gen4/EncounterArea4.cpp
Source/Core/Resources/i18n/de/hgss_de.txt
Source/Core/Resources/i18n/en/hgss_en.txt
Source/Core/Resources/i18n/fr/hgss_fr.txt
Source/Core/Resources/i18n/ja/hgss_ja.txt
Source/Core/Resources/i18n/ko/hgss_ko.txt
Source/Core/Resources/i18n/zh/hgss_zh.txt

[Gen 4] Reanmed location Rock Tunnel 2F to Rock Tunnel B1F

---

Source/Core/Gen5/Searchers/Searcher5.hpp

Fix gen5 searcher

---

Source/Core/Resources/i18n/de/bw2_de.txt

Forgot to translate it last time

Fix Route 6 (Mistralton Cave) German Translation

---

Source/Core/Resources/i18n/de/bw2_de.txt

Didnt fully translate it prior

Fix BW2 location 80 translation

---

.github/workflows/macos.yaml
.github/workflows/ubuntu.yaml
.github/workflows/windows.yaml

This PR works to help solve actions running twice for PR pushes. Solution found and described here: https://github.com/orgs/community/discussions/57827

Fix doubling up actions in PRs

---

Source/Core/Gen4/EncounterArea4.hpp
Source/Core/Gen4/Generators/WildGenerator4.cpp

Battle advances delay fix

---

README.md

Old link doesn't work anymore.

Fix Visual C++ redistributable link on ReadMe
